"""add guild_settings table

Revision ID: 1e9473901cf3
Revises: c89d3d8c7527
Create Date: 2026-04-01 18:54:18.427892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9473901cf3'
down_revision: Union[str, None] = 'c89d3d8c7527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_settings',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('summary_mode', sa.String(length=20), nullable=False),
    sa.Column('summary_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_settings_guild_id'), 'guild_settings', ['guild_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guild_settings_guild_id'), table_name='guild_settings')
    op.drop_table('guild_settings')
    # ### end Alembic commands ###
