"""add user_links table

Revision ID: d0445d51001d
Revises: ea5dea190f25
Create Date: 2026-04-04 10:39:02.815172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0445d51001d'
down_revision: Union[str, None] = 'ea5dea190f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_links',
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('stripe_product_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_links_discord_user_id'), 'user_links', ['discord_user_id'], unique=True)
    op.create_index(op.f('ix_user_links_email'), 'user_links', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_links_email'), table_name='user_links')
    op.drop_index(op.f('ix_user_links_discord_user_id'), table_name='user_links')
    op.drop_table('user_links')
    # ### end Alembic commands ###
