"""move summary settings to campaign table

Revision ID: ea5dea190f25
Revises: 0b5c70630ed5
Create Date: 2026-04-02 12:25:51.140475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea5dea190f25'
down_revision: Union[str, None] = '0b5c70630ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guild_settings_guild_id'), table_name='guild_settings')
    op.drop_table('guild_settings')
    op.add_column('campaigns', sa.Column('summary_channel_id', sa.BigInteger(), nullable=True))
    op.add_column('campaigns', sa.Column('summary_mode', sa.String(length=20), server_default='channel', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'summary_mode')
    op.drop_column('campaigns', 'summary_channel_id')
    op.create_table('guild_settings',
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('summary_mode', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('summary_channel_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('guild_settings_pkey'))
    )
    op.create_index(op.f('ix_guild_settings_guild_id'), 'guild_settings', ['guild_id'], unique=True)
    # ### end Alembic commands ###
